# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autoridad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_autoridad', models.CharField(max_length=255)),
                ('fechainicio_autoridad', models.DateField()),
                ('firma_autoridad', models.ImageField(upload_to='firmas_autoridad')),
            ],
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_licencias', models.CharField(max_length=6)),
                ('fecha_expedicion', models.DateField()),
                ('fecha_revalidacion', models.DateField()),
                ('restricciones', models.CharField(max_length=6)),
                ('autoridad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Autoridad')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('dni', models.CharField(max_length=8)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=255)),
                ('donacion', models.BooleanField(default=True)),
                ('foto', models.ImageField(upload_to='fotos')),
                ('firma', models.ImageField(upload_to='firmas')),
            ],
        ),
        migrations.AddField(
            model_name='licencia',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Persona'),
        ),
    ]
