# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autoridad',
            options={'verbose_name_plural': 'Autoridades'},
        ),
    ]
